variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: "0"

stages:
  - build

before_script:
  - export VERSION_MAJOR_MINOR=`cat VERSION`
  - export VERSION=`greycat build-version`
  - echo "${VERSION_MAJOR_MINOR} / ${VERSION}"

x64-linux:
  stage: build
  tags: [ linux ]
  script:
    - cargo build --release --target=x86_64-unknown-linux-gnu
    - cargo test

arm64-apple:
  stage: build
  tags: [ macos_native ]
  script:
    - cargo build --release --target=aarch64-apple-darwin
    - cargo test

x64-windows:
  stage: build
  tags: [ mingw ]
  script:
    - cargo build --release --target=x86_64-pc-windows-gnu
    - cargo test