[workspace]
members = [
  "greycat-sys",
  "greycat-macro",
  "greycat",
  "cargo-greycat",
  # "greycat-sdk",
  # "greycat-cli",
]
exclude = ["examples"]
resolver = "2"

[workspace.package]
version = "7.4.0-dev"
edition = "2021"
authors = ["Maxime Tricoire <maxime.tricoire@datathings.com>"]
license = "Apache-2.0"

[workspace.dependencies]
greycat-macro = { path = "./greycat-macro" }
greycat-sys = { path = "./greycat-sys" }
greycat = { path = "./greycat" }
# greycat-sdk = { path = "./greycat-sdk" }
# greycat-cli = { path = "./greycat-cli" }
anyhow = { version = "1.0.100" }

[profile.release]
strip = true
lto = true
panic = "abort"
