[package]
name = "greycat-sdk"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0.75"
byteorder = "1.5.0"
ordered-float = { version = "4.1.1", features = ["serde"] }
serde = { workspace = true, features = ["derive", "rc"] }
greycat = { workspace = true }
morton-encoding = "2.0.1"
chrono = "0.4.31"
serde_json = { workspace = true }
