// AUTOMATICALLY GENERATED BY 'greycat codegen'
#![allow(non_snake_case)]

use greycat::GcString;

#[global_allocator]
static GLOBAL: ::greycat::GreyCatAlloc = ::greycat::GreyCatAlloc;

#[unsafe(no_mangle)]
pub unsafe extern "C" fn gc_lib_csv2__link(
    prog: *mut ::greycat::sys::gc_program_t,
    lib: *mut ::greycat::sys::gc_program_library_t,
) -> bool {
    let __gc_prog = ::greycat::GcProgramMut(prog);
    unsafe {
        ::greycat::sys::gc_program_library__set_lib_hooks(
            lib,
            Some(csv2_start),
            Some(csv2_stop),
        );
    }

    let csv2 = __gc_prog.resolve_module("csv2");
    let csv2_CsvReader = __gc_prog.resolve_type(csv2, "CsvReader");
    __gc_prog.configure_type(
        csv2_CsvReader,
        ::std::mem::size_of::<crate::csv2::CsvReader>(),
        crate::csv2::_gc_CsvReader_finalize,
    );
    __gc_prog.link_type_fn(csv2_CsvReader, "can_read", crate::csv2::_gc_CsvReader__can_read);
    __gc_prog.link_type_fn(csv2_CsvReader, "read", crate::csv2::_gc_CsvReader__read);

    true
}

unsafe extern "C" fn csv2_start(
    _lib: *mut ::greycat::sys::gc_program_library_t,
    prog: *mut ::greycat::sys::gc_program_t,
    userdata: *mut *mut ::core::ffi::c_void,
) -> bool {
    use ::greycat::GcLibrary as _;
    let prog = ::greycat::GcProgramMut(prog);
    match crate::LibState::start(prog) {
      Ok(Some(data)) => {
          let data = Box::new(data);
          unsafe { *userdata = Box::into_raw(data) as *mut _ };
          true
      }
      Ok(None) => true,
      Err(_) => false,
    }
}

unsafe extern "C" fn csv2_stop(
    _lib: *mut ::greycat::sys::gc_program_library_t,
    prog: *mut ::greycat::sys::gc_program_t,
    userdata: *mut *mut ::core::ffi::c_void,
) -> bool {
    use ::greycat::GcLibrary as _;
    let prog = ::greycat::GcProgramMut(prog);
    let state = unsafe { crate::LibState::load(userdata) };
    crate::LibState::stop(prog, state).is_ok()
}

impl crate::csv2::CsvReader {
    pub fn path(&self, ctx: ::greycat::GcMachine) -> GcString {
        use ::greycat::ObjectGetAt as _;
        unsafe { self.__header.get_at(0, ctx) }
    }
}
