// AUTOMATICALLY GENERATED BY 'greycat codegen'
#![allow(non_snake_case, non_upper_case_globals, unused)]

#[global_allocator]
static GLOBAL: ::greycat::GreyCatAlloc = ::greycat::GreyCatAlloc;

::greycat::gc_type_id!(core_GeoCircle);
::greycat::gc_type_id!(core_Tuple__int_any_null);
::greycat::gc_type_id!(core_VectorIndex);
::greycat::gc_type_id!(core_Array__Role);
::greycat::gc_type_id!(core_str);
::greycat::gc_type_id!(core_Array__Permission);
::greycat::gc_type_id!(core_Array__Frame);
::greycat::gc_type_id!(core_Map__String_MediaTypeObject);
::greycat::gc_type_id!(core_Array__ErrorFrame);
::greycat::gc_type_id!(core_float);
::greycat::gc_type_id!(core_t3f);
::greycat::gc_type_id!(core_GeoBox);
::greycat::gc_type_id!(core_Array__ResponseObject);
::greycat::gc_type_id!(core_Array__PathItemObject);
::greycat::gc_type_id!(core_nodeTime);
::greycat::gc_type_id!(core_Table__GaussianProfileSlot_null);
::greycat::gc_type_id!(core_nodeIndexBucket);
::greycat::gc_type_id!(core_Array__node_null);
::greycat::gc_type_id!(core_Array__HistogramBin);
::greycat::gc_type_id!(core_String);
::greycat::gc_type_id!(core_NodeInfo__int);
::greycat::gc_type_id!(core_field);
::greycat::gc_type_id!(core_nodeList);
::greycat::gc_type_id!(core_t3);
::greycat::gc_type_id!(core_time);
::greycat::gc_type_id!(core_Table__Tuple__float_any_null);
::greycat::gc_type_id!(core_Array__MediaTypeObject);
::greycat::gc_type_id!(core_Array__SearchResult);
::greycat::gc_type_id!(core_Tensor);
::greycat::gc_type_id!(core_Array__HeaderObject);
::greycat::gc_type_id!(core_geo);
::greycat::gc_type_id!(core_Map__String_UserCredential);
::greycat::gc_type_id!(core_NodeInfo__time);
::greycat::gc_type_id!(core_Buffer);
::greycat::gc_type_id!(core_Date);
::greycat::gc_type_id!(core_Array__UserGroupPolicy);
::greycat::gc_type_id!(core_ErrorFrame);
::greycat::gc_type_id!(core_TableColumnMapping);
::greycat::gc_type_id!(core_Map__String_PathItemObject);
::greycat::gc_type_id!(core_Array__PeriodicTask);
::greycat::gc_type_id!(core_Tuple__time_any_null);
::greycat::gc_type_id!(core_Array__DateTuple);
::greycat::gc_type_id!(core_Array__SchemaObject);
::greycat::gc_type_id!(core_Array__File);
::greycat::gc_type_id!(core_GeoPoly);
::greycat::gc_type_id!(core_nodeList__nodeList__VectorLeaf);
::greycat::gc_type_id!(core_null);
::greycat::gc_type_id!(core_type);
::greycat::gc_type_id!(core_t4f);
::greycat::gc_type_id!(core_Array__NodeInfo__geo);
::greycat::gc_type_id!(core_node);
::greycat::gc_type_id!(core_Error);
::greycat::gc_type_id!(core_Array__NodeInfo);
::greycat::gc_type_id!(core_Array__TableColumnMapping);
::greycat::gc_type_id!(core_Array__Job);
::greycat::gc_type_id!(core_Vector);
::greycat::gc_type_id!(core_Array__geo);
::greycat::gc_type_id!(core_Array__String);
::greycat::gc_type_id!(core_Array__any);
::greycat::gc_type_id!(core_nodeIndex);
::greycat::gc_type_id!(core_Tuple__int_VectorLeaf);
::greycat::gc_type_id!(core_Tuple__float_any_null);
::greycat::gc_type_id!(core_Map__String_HeaderObject);
::greycat::gc_type_id!(core_NodeInfo__geo);
::greycat::gc_type_id!(core_Map__String_SchemaObject);
::greycat::gc_type_id!(core_Map__String_int);
::greycat::gc_type_id!(core_Array__Quantizer);
::greycat::gc_type_id!(core_Map__String_ResponseObject);
::greycat::gc_type_id!(core_Array__Variable);
::greycat::gc_type_id!(core_Tuple__int_nodeList__VectorLeaf);
::greycat::gc_type_id!(core_Array__CsvColumnStatistics);
::greycat::gc_type_id!(core_Table);
::greycat::gc_type_id!(core_MathConstants);
::greycat::gc_type_id!(core_Array__Task);
::greycat::gc_type_id!(core_bool);
::greycat::gc_type_id!(core_Array__nodeTime);
::greycat::gc_type_id!(core_Array__nodeList);
::greycat::gc_type_id!(core_Array__nodeIndex);
::greycat::gc_type_id!(core_Map__any_int);
::greycat::gc_type_id!(core_Array__SecurityEntity);
::greycat::gc_type_id!(core_Array__NodeInfo__int);
::greycat::gc_type_id!(core_Array__int_null);
::greycat::gc_type_id!(core_Array__int);
::greycat::gc_type_id!(core_duration);
::greycat::gc_type_id!(core_nodeList__VectorLeaf);
::greycat::gc_type_id!(core_Array);
::greycat::gc_type_id!(core_Array__DayOfWeek);
::greycat::gc_type_id!(core_Tuple);
::greycat::gc_type_id!(core_Map);
::greycat::gc_type_id!(core_nodeGeo);
::greycat::gc_type_id!(core_Array__field);
::greycat::gc_type_id!(core_any);
::greycat::gc_type_id!(core_char);
::greycat::gc_type_id!(core_Array__nodeGeo);
::greycat::gc_type_id!(core_nodeTimeCursor);
::greycat::gc_type_id!(core_Array__UserCredential);
::greycat::gc_type_id!(core_int);
::greycat::gc_type_id!(core_Map__String_String);
::greycat::gc_type_id!(core_Table__Tuple__time_any_null);
::greycat::gc_type_id!(core_t2);
::greycat::gc_type_id!(core_t2f);
::greycat::gc_type_id!(core_SearchResult);
::greycat::gc_type_id!(core_function);
::greycat::gc_type_id!(core_Array__float);
::greycat::gc_type_id!(core_VectorLeaf);
::greycat::gc_type_id!(core_NodeInfo);
::greycat::gc_type_id!(core_Tuple__geo_any_null);
::greycat::gc_type_id!(core_t4);
::greycat::gc_type_id!(core_Array__NodeInfo__time);
::greycat::gc_type_id!(runtime_Runtime);
::greycat::gc_type_id!(runtime_ChildProcess);
::greycat::gc_type_id!(runtime_Periodicity);
::greycat::gc_type_id!(runtime_UserGroupPolicy);
::greycat::gc_type_id!(runtime_Variable);
::greycat::gc_type_id!(runtime_OpenApiV3);
::greycat::gc_type_id!(runtime_OperationObject);
::greycat::gc_type_id!(runtime_License);
::greycat::gc_type_id!(runtime_FixedPeriodicity);
::greycat::gc_type_id!(runtime_MonthlyPeriodicity);
::greycat::gc_type_id!(runtime_RuntimeInfo);
::greycat::gc_type_id!(runtime_LogDataUsage);
::greycat::gc_type_id!(runtime_Debug);
::greycat::gc_type_id!(runtime_Scheduler);
::greycat::gc_type_id!(runtime_SecurityFields);
::greycat::gc_type_id!(runtime_MediaTypeObject);
::greycat::gc_type_id!(runtime_Log);
::greycat::gc_type_id!(runtime_InfoObject);
::greycat::gc_type_id!(runtime_SecurityPolicy);
::greycat::gc_type_id!(runtime_Task);
::greycat::gc_type_id!(runtime_UserGroup);
::greycat::gc_type_id!(runtime_SchemaObject);
::greycat::gc_type_id!(runtime_YearlyPeriodicity);
::greycat::gc_type_id!(runtime_System);
::greycat::gc_type_id!(runtime_DateTuple);
::greycat::gc_type_id!(runtime_Role);
::greycat::gc_type_id!(runtime_ResponseObject);
::greycat::gc_type_id!(runtime_User);
::greycat::gc_type_id!(runtime_Job);
::greycat::gc_type_id!(runtime_Permission);
::greycat::gc_type_id!(runtime_WeeklyPeriodicity);
::greycat::gc_type_id!(runtime_ComponentsObject);
::greycat::gc_type_id!(runtime_PeriodicTask);
::greycat::gc_type_id!(runtime_PeriodicOptions);
::greycat::gc_type_id!(runtime_UserCredential);
::greycat::gc_type_id!(runtime_ChildProcessResult);
::greycat::gc_type_id!(runtime_DailyPeriodicity);
::greycat::gc_type_id!(runtime_Frame);
::greycat::gc_type_id!(runtime_RequestBodyObject);
::greycat::gc_type_id!(runtime_HeaderObject);
::greycat::gc_type_id!(runtime_OpenApi);
::greycat::gc_type_id!(runtime_PathItemObject);
::greycat::gc_type_id!(runtime_OpenIDConnect);
::greycat::gc_type_id!(runtime_SecurityEntity);
::greycat::gc_type_id!(io_GcbWriter);
::greycat::gc_type_id!(io_HttpResponse);
::greycat::gc_type_id!(io_Writer);
::greycat::gc_type_id!(io_GcbReader);
::greycat::gc_type_id!(io_CsvStatistics);
::greycat::gc_type_id!(io_Http);
::greycat::gc_type_id!(io_Url);
::greycat::gc_type_id!(io_TextReader);
::greycat::gc_type_id!(io_CsvFormat);
::greycat::gc_type_id!(io_JsonWriter);
::greycat::gc_type_id!(io_CsvAnalysisConfig);
::greycat::gc_type_id!(io_HttpRequest);
::greycat::gc_type_id!(io_FileWalker);
::greycat::gc_type_id!(io_Csv);
::greycat::gc_type_id!(io_Json);
::greycat::gc_type_id!(io_Reader);
::greycat::gc_type_id!(io_JsonReader);
::greycat::gc_type_id!(io_CsvColumnStatistics);
::greycat::gc_type_id!(io_File);
::greycat::gc_type_id!(io_Smtp);
::greycat::gc_type_id!(io_Reader__String);
::greycat::gc_type_id!(io_CsvWriter);
::greycat::gc_type_id!(io_CsvSharding);
::greycat::gc_type_id!(io_TextWriter);
::greycat::gc_type_id!(io_Email);
::greycat::gc_type_id!(io_XmlReader);
::greycat::gc_type_id!(io_CsvReader);
::greycat::gc_type_id!(util_ProgressTracker);
::greycat::gc_type_id!(util_Random);
::greycat::gc_type_id!(util_SlidingWindow);
::greycat::gc_type_id!(util_LinearQuantizer);
::greycat::gc_type_id!(util_Stack);
::greycat::gc_type_id!(util_Quantizer__Array);
::greycat::gc_type_id!(util_Histogram);
::greycat::gc_type_id!(util_Queue);
::greycat::gc_type_id!(util_QuantizerSlotBound);
::greycat::gc_type_id!(util_Quantizer);
::greycat::gc_type_id!(util_CustomQuantizer);
::greycat::gc_type_id!(util_GaussianProfileSlot);
::greycat::gc_type_id!(util_QuantizerSlotBound__Array);
::greycat::gc_type_id!(util_Crypto);
::greycat::gc_type_id!(util_HistogramBin);
::greycat::gc_type_id!(util_Gaussian);
::greycat::gc_type_id!(util_GaussianProfile);
::greycat::gc_type_id!(util_Plot);
::greycat::gc_type_id!(util_LogQuantizer);
::greycat::gc_type_id!(util_TimeWindow);
::greycat::gc_type_id!(util_MultiQuantizer);
::greycat::gc_type_id!(util_Assert);
::greycat::gc_type_id!(util_HistogramStats);
::greycat::gc_type_id!(project_Record);
::greycat::gc_type_id!(project_Root);
::greycat::gc_type_id!(csv2_CsvReader__Record);
::greycat::gc_type_id!(csv2_CsvOptions);
::greycat::gc_type_id!(csv2_CsvReader);

pub(crate) const csv2_CsvTrim_Headers: u32 = 0;
pub(crate) const csv2_CsvTrim_Fields: u32 = 1;
pub(crate) const csv2_CsvTrim_All: u32 = 2;
pub(crate) const csv2_CsvOptions_has_header: u32 = 0;
pub(crate) const csv2_CsvOptions_delimiter: u32 = 1;
pub(crate) const csv2_CsvOptions_flexible: u32 = 2;
pub(crate) const csv2_CsvOptions_trim: u32 = 3;
pub(crate) const csv2_CsvReader_path: u32 = 0;
pub(crate) const csv2_CsvReader_options: u32 = 1;

#[unsafe(no_mangle)]
pub unsafe extern "C" fn gc_lib_csv2__link(
    prog: *mut ::greycat::sys::gc_program_t,
    lib: *mut ::greycat::sys::gc_program_library_t,
) -> bool {
    unsafe {
        ::greycat::sys::gc_program_library__set_lib_hooks(lib, Some(csv2_start), Some(csv2_stop));
    }
    csv2_link(::greycat::GcProgramMut(prog)).is_some()
}

unsafe extern "C" fn csv2_start(
    _lib: *mut ::greycat::sys::gc_program_library_t,
    prog: *mut ::greycat::sys::gc_program_t,
    userdata: *mut *mut ::core::ffi::c_void,
) -> bool {
    use ::greycat::GcLibrary as _;
    let prog = ::greycat::GcProgramMut(prog);
    match crate::Library::start(prog) {
      Ok(Some(data)) => {
          let data = Box::new(data);
          unsafe { *userdata = Box::into_raw(data) as *mut _ };
          true
      }
      Ok(None) => true,
      Err(_) => false,
    }
}

unsafe extern "C" fn csv2_stop(
    _lib: *mut ::greycat::sys::gc_program_library_t,
    prog: *mut ::greycat::sys::gc_program_t,
    userdata: *mut *mut ::core::ffi::c_void,
) -> bool {
    use ::greycat::GcLibrary as _;
    let prog = ::greycat::GcProgramMut(prog);
    let state = unsafe { crate::Library::load(userdata) };
    crate::Library::stop(prog, state).is_ok()
}

#[rustfmt::skip]
fn csv2_link(__prg: ::greycat::GcProgramMut) -> Option<()> {
    unsafe {
        let core = __prg.resolve_module("core")?;
        _core_GeoCircle = __prg.resolve_type(core, "GeoCircle")?;
        _core_Tuple__int_any_null = __prg.resolve_type(core, "Tuple<core::int,core::any?>")?;
        _core_VectorIndex = __prg.resolve_type(core, "VectorIndex")?;
        _core_Array__Role = __prg.resolve_type(core, "Array<runtime::Role>")?;
        _core_str = __prg.resolve_type(core, "str")?;
        _core_Array__Permission = __prg.resolve_type(core, "Array<runtime::Permission>")?;
        _core_Array__Frame = __prg.resolve_type(core, "Array<runtime::Frame>")?;
        _core_Map__String_MediaTypeObject = __prg.resolve_type(core, "Map<core::String,runtime::MediaTypeObject>")?;
        _core_Array__ErrorFrame = __prg.resolve_type(core, "Array<core::ErrorFrame>")?;
        _core_float = __prg.resolve_type(core, "float")?;
        _core_t3f = __prg.resolve_type(core, "t3f")?;
        _core_GeoBox = __prg.resolve_type(core, "GeoBox")?;
        _core_Array__ResponseObject = __prg.resolve_type(core, "Array<runtime::ResponseObject>")?;
        _core_Array__PathItemObject = __prg.resolve_type(core, "Array<runtime::PathItemObject>")?;
        _core_nodeTime = __prg.resolve_type(core, "nodeTime")?;
        _core_Table__GaussianProfileSlot_null = __prg.resolve_type(core, "Table<util::GaussianProfileSlot?>")?;
        _core_nodeIndexBucket = __prg.resolve_type(core, "nodeIndexBucket")?;
        _core_Array__node_null = __prg.resolve_type(core, "Array<core::node?>")?;
        _core_Array__HistogramBin = __prg.resolve_type(core, "Array<util::HistogramBin>")?;
        _core_String = __prg.resolve_type(core, "String")?;
        _core_NodeInfo__int = __prg.resolve_type(core, "NodeInfo<core::int>")?;
        _core_field = __prg.resolve_type(core, "field")?;
        _core_nodeList = __prg.resolve_type(core, "nodeList")?;
        _core_t3 = __prg.resolve_type(core, "t3")?;
        _core_time = __prg.resolve_type(core, "time")?;
        _core_Table__Tuple__float_any_null = __prg.resolve_type(core, "Table<core::Tuple<core::float,core::any?>>")?;
        _core_Array__MediaTypeObject = __prg.resolve_type(core, "Array<runtime::MediaTypeObject>")?;
        _core_Array__SearchResult = __prg.resolve_type(core, "Array<core::SearchResult>")?;
        _core_Tensor = __prg.resolve_type(core, "Tensor")?;
        _core_Array__HeaderObject = __prg.resolve_type(core, "Array<runtime::HeaderObject>")?;
        _core_geo = __prg.resolve_type(core, "geo")?;
        _core_Map__String_UserCredential = __prg.resolve_type(core, "Map<core::String,runtime::UserCredential>")?;
        _core_NodeInfo__time = __prg.resolve_type(core, "NodeInfo<core::time>")?;
        _core_Buffer = __prg.resolve_type(core, "Buffer")?;
        _core_Date = __prg.resolve_type(core, "Date")?;
        _core_Array__UserGroupPolicy = __prg.resolve_type(core, "Array<runtime::UserGroupPolicy>")?;
        _core_ErrorFrame = __prg.resolve_type(core, "ErrorFrame")?;
        _core_TableColumnMapping = __prg.resolve_type(core, "TableColumnMapping")?;
        _core_Map__String_PathItemObject = __prg.resolve_type(core, "Map<core::String,runtime::PathItemObject>")?;
        _core_Array__PeriodicTask = __prg.resolve_type(core, "Array<runtime::PeriodicTask>")?;
        _core_Tuple__time_any_null = __prg.resolve_type(core, "Tuple<core::time,core::any?>")?;
        _core_Array__DateTuple = __prg.resolve_type(core, "Array<runtime::DateTuple>")?;
        _core_Array__SchemaObject = __prg.resolve_type(core, "Array<runtime::SchemaObject>")?;
        _core_Array__File = __prg.resolve_type(core, "Array<io::File>")?;
        _core_GeoPoly = __prg.resolve_type(core, "GeoPoly")?;
        _core_nodeList__nodeList__VectorLeaf = __prg.resolve_type(core, "nodeList<core::nodeList<core::VectorLeaf>>")?;
        _core_null = __prg.resolve_type(core, "null")?;
        _core_type = __prg.resolve_type(core, "type")?;
        _core_t4f = __prg.resolve_type(core, "t4f")?;
        _core_Array__NodeInfo__geo = __prg.resolve_type(core, "Array<core::NodeInfo<core::geo>>")?;
        _core_node = __prg.resolve_type(core, "node")?;
        _core_Error = __prg.resolve_type(core, "Error")?;
        _core_Array__NodeInfo = __prg.resolve_type(core, "Array<core::NodeInfo>")?;
        _core_Array__TableColumnMapping = __prg.resolve_type(core, "Array<core::TableColumnMapping>")?;
        _core_Array__Job = __prg.resolve_type(core, "Array<runtime::Job>")?;
        _core_Vector = __prg.resolve_type(core, "Vector")?;
        _core_Array__geo = __prg.resolve_type(core, "Array<core::geo>")?;
        _core_Array__String = __prg.resolve_type(core, "Array<core::String>")?;
        _core_Array__any = __prg.resolve_type(core, "Array<core::any>")?;
        _core_nodeIndex = __prg.resolve_type(core, "nodeIndex")?;
        _core_Tuple__int_VectorLeaf = __prg.resolve_type(core, "Tuple<core::int,core::VectorLeaf>")?;
        _core_Tuple__float_any_null = __prg.resolve_type(core, "Tuple<core::float,core::any?>")?;
        _core_Map__String_HeaderObject = __prg.resolve_type(core, "Map<core::String,runtime::HeaderObject>")?;
        _core_NodeInfo__geo = __prg.resolve_type(core, "NodeInfo<core::geo>")?;
        _core_Map__String_SchemaObject = __prg.resolve_type(core, "Map<core::String,runtime::SchemaObject>")?;
        _core_Map__String_int = __prg.resolve_type(core, "Map<core::String,core::int>")?;
        _core_Array__Quantizer = __prg.resolve_type(core, "Array<util::Quantizer>")?;
        _core_Map__String_ResponseObject = __prg.resolve_type(core, "Map<core::String,runtime::ResponseObject>")?;
        _core_Array__Variable = __prg.resolve_type(core, "Array<runtime::Variable>")?;
        _core_Tuple__int_nodeList__VectorLeaf = __prg.resolve_type(core, "Tuple<core::int,core::nodeList<core::VectorLeaf>>")?;
        _core_Array__CsvColumnStatistics = __prg.resolve_type(core, "Array<io::CsvColumnStatistics>")?;
        _core_Table = __prg.resolve_type(core, "Table")?;
        _core_MathConstants = __prg.resolve_type(core, "MathConstants")?;
        _core_Array__Task = __prg.resolve_type(core, "Array<runtime::Task>")?;
        _core_bool = __prg.resolve_type(core, "bool")?;
        _core_Array__nodeTime = __prg.resolve_type(core, "Array<core::nodeTime>")?;
        _core_Array__nodeList = __prg.resolve_type(core, "Array<core::nodeList>")?;
        _core_Array__nodeIndex = __prg.resolve_type(core, "Array<core::nodeIndex>")?;
        _core_Map__any_int = __prg.resolve_type(core, "Map<core::any,core::int>")?;
        _core_Array__SecurityEntity = __prg.resolve_type(core, "Array<runtime::SecurityEntity>")?;
        _core_Array__NodeInfo__int = __prg.resolve_type(core, "Array<core::NodeInfo<core::int>>")?;
        _core_Array__int_null = __prg.resolve_type(core, "Array<core::int?>")?;
        _core_Array__int = __prg.resolve_type(core, "Array<core::int>")?;
        _core_duration = __prg.resolve_type(core, "duration")?;
        _core_nodeList__VectorLeaf = __prg.resolve_type(core, "nodeList<core::VectorLeaf>")?;
        _core_Array = __prg.resolve_type(core, "Array")?;
        _core_Array__DayOfWeek = __prg.resolve_type(core, "Array<runtime::DayOfWeek>")?;
        _core_Tuple = __prg.resolve_type(core, "Tuple")?;
        _core_Map = __prg.resolve_type(core, "Map")?;
        _core_nodeGeo = __prg.resolve_type(core, "nodeGeo")?;
        _core_Array__field = __prg.resolve_type(core, "Array<core::field>")?;
        _core_any = __prg.resolve_type(core, "any")?;
        _core_char = __prg.resolve_type(core, "char")?;
        _core_Array__nodeGeo = __prg.resolve_type(core, "Array<core::nodeGeo>")?;
        _core_nodeTimeCursor = __prg.resolve_type(core, "nodeTimeCursor")?;
        _core_Array__UserCredential = __prg.resolve_type(core, "Array<runtime::UserCredential>")?;
        _core_int = __prg.resolve_type(core, "int")?;
        _core_Map__String_String = __prg.resolve_type(core, "Map<core::String,core::String>")?;
        _core_Table__Tuple__time_any_null = __prg.resolve_type(core, "Table<core::Tuple<core::time,core::any?>>")?;
        _core_t2 = __prg.resolve_type(core, "t2")?;
        _core_t2f = __prg.resolve_type(core, "t2f")?;
        _core_SearchResult = __prg.resolve_type(core, "SearchResult")?;
        _core_function = __prg.resolve_type(core, "function")?;
        _core_Array__float = __prg.resolve_type(core, "Array<core::float>")?;
        _core_VectorLeaf = __prg.resolve_type(core, "VectorLeaf")?;
        _core_NodeInfo = __prg.resolve_type(core, "NodeInfo")?;
        _core_Tuple__geo_any_null = __prg.resolve_type(core, "Tuple<core::geo,core::any?>")?;
        _core_t4 = __prg.resolve_type(core, "t4")?;
        _core_Array__NodeInfo__time = __prg.resolve_type(core, "Array<core::NodeInfo<core::time>>")?;
        let runtime = __prg.resolve_module("runtime")?;
        _runtime_Runtime = __prg.resolve_type(runtime, "Runtime")?;
        _runtime_ChildProcess = __prg.resolve_type(runtime, "ChildProcess")?;
        _runtime_Periodicity = __prg.resolve_type(runtime, "Periodicity")?;
        _runtime_UserGroupPolicy = __prg.resolve_type(runtime, "UserGroupPolicy")?;
        _runtime_Variable = __prg.resolve_type(runtime, "Variable")?;
        _runtime_OpenApiV3 = __prg.resolve_type(runtime, "OpenApiV3")?;
        _runtime_OperationObject = __prg.resolve_type(runtime, "OperationObject")?;
        _runtime_License = __prg.resolve_type(runtime, "License")?;
        _runtime_FixedPeriodicity = __prg.resolve_type(runtime, "FixedPeriodicity")?;
        _runtime_MonthlyPeriodicity = __prg.resolve_type(runtime, "MonthlyPeriodicity")?;
        _runtime_RuntimeInfo = __prg.resolve_type(runtime, "RuntimeInfo")?;
        _runtime_LogDataUsage = __prg.resolve_type(runtime, "LogDataUsage")?;
        _runtime_Debug = __prg.resolve_type(runtime, "Debug")?;
        _runtime_Scheduler = __prg.resolve_type(runtime, "Scheduler")?;
        _runtime_SecurityFields = __prg.resolve_type(runtime, "SecurityFields")?;
        _runtime_MediaTypeObject = __prg.resolve_type(runtime, "MediaTypeObject")?;
        _runtime_Log = __prg.resolve_type(runtime, "Log")?;
        _runtime_InfoObject = __prg.resolve_type(runtime, "InfoObject")?;
        _runtime_SecurityPolicy = __prg.resolve_type(runtime, "SecurityPolicy")?;
        _runtime_Task = __prg.resolve_type(runtime, "Task")?;
        _runtime_UserGroup = __prg.resolve_type(runtime, "UserGroup")?;
        _runtime_SchemaObject = __prg.resolve_type(runtime, "SchemaObject")?;
        _runtime_YearlyPeriodicity = __prg.resolve_type(runtime, "YearlyPeriodicity")?;
        _runtime_System = __prg.resolve_type(runtime, "System")?;
        _runtime_DateTuple = __prg.resolve_type(runtime, "DateTuple")?;
        _runtime_Role = __prg.resolve_type(runtime, "Role")?;
        _runtime_ResponseObject = __prg.resolve_type(runtime, "ResponseObject")?;
        _runtime_User = __prg.resolve_type(runtime, "User")?;
        _runtime_Job = __prg.resolve_type(runtime, "Job")?;
        _runtime_Permission = __prg.resolve_type(runtime, "Permission")?;
        _runtime_WeeklyPeriodicity = __prg.resolve_type(runtime, "WeeklyPeriodicity")?;
        _runtime_ComponentsObject = __prg.resolve_type(runtime, "ComponentsObject")?;
        _runtime_PeriodicTask = __prg.resolve_type(runtime, "PeriodicTask")?;
        _runtime_PeriodicOptions = __prg.resolve_type(runtime, "PeriodicOptions")?;
        _runtime_UserCredential = __prg.resolve_type(runtime, "UserCredential")?;
        _runtime_ChildProcessResult = __prg.resolve_type(runtime, "ChildProcessResult")?;
        _runtime_DailyPeriodicity = __prg.resolve_type(runtime, "DailyPeriodicity")?;
        _runtime_Frame = __prg.resolve_type(runtime, "Frame")?;
        _runtime_RequestBodyObject = __prg.resolve_type(runtime, "RequestBodyObject")?;
        _runtime_HeaderObject = __prg.resolve_type(runtime, "HeaderObject")?;
        _runtime_OpenApi = __prg.resolve_type(runtime, "OpenApi")?;
        _runtime_PathItemObject = __prg.resolve_type(runtime, "PathItemObject")?;
        _runtime_OpenIDConnect = __prg.resolve_type(runtime, "OpenIDConnect")?;
        _runtime_SecurityEntity = __prg.resolve_type(runtime, "SecurityEntity")?;
        let io = __prg.resolve_module("io")?;
        _io_GcbWriter = __prg.resolve_type(io, "GcbWriter")?;
        _io_HttpResponse = __prg.resolve_type(io, "HttpResponse")?;
        _io_Writer = __prg.resolve_type(io, "Writer")?;
        _io_GcbReader = __prg.resolve_type(io, "GcbReader")?;
        _io_CsvStatistics = __prg.resolve_type(io, "CsvStatistics")?;
        _io_Http = __prg.resolve_type(io, "Http")?;
        _io_Url = __prg.resolve_type(io, "Url")?;
        _io_TextReader = __prg.resolve_type(io, "TextReader")?;
        _io_CsvFormat = __prg.resolve_type(io, "CsvFormat")?;
        _io_JsonWriter = __prg.resolve_type(io, "JsonWriter")?;
        _io_CsvAnalysisConfig = __prg.resolve_type(io, "CsvAnalysisConfig")?;
        _io_HttpRequest = __prg.resolve_type(io, "HttpRequest")?;
        _io_FileWalker = __prg.resolve_type(io, "FileWalker")?;
        _io_Csv = __prg.resolve_type(io, "Csv")?;
        _io_Json = __prg.resolve_type(io, "Json")?;
        _io_Reader = __prg.resolve_type(io, "Reader")?;
        _io_JsonReader = __prg.resolve_type(io, "JsonReader")?;
        _io_CsvColumnStatistics = __prg.resolve_type(io, "CsvColumnStatistics")?;
        _io_File = __prg.resolve_type(io, "File")?;
        _io_Smtp = __prg.resolve_type(io, "Smtp")?;
        _io_Reader__String = __prg.resolve_type(io, "Reader<core::String>")?;
        _io_CsvWriter = __prg.resolve_type(io, "CsvWriter")?;
        _io_CsvSharding = __prg.resolve_type(io, "CsvSharding")?;
        _io_TextWriter = __prg.resolve_type(io, "TextWriter")?;
        _io_Email = __prg.resolve_type(io, "Email")?;
        _io_XmlReader = __prg.resolve_type(io, "XmlReader")?;
        _io_CsvReader = __prg.resolve_type(io, "CsvReader")?;
        let util = __prg.resolve_module("util")?;
        _util_ProgressTracker = __prg.resolve_type(util, "ProgressTracker")?;
        _util_Random = __prg.resolve_type(util, "Random")?;
        _util_SlidingWindow = __prg.resolve_type(util, "SlidingWindow")?;
        _util_LinearQuantizer = __prg.resolve_type(util, "LinearQuantizer")?;
        _util_Stack = __prg.resolve_type(util, "Stack")?;
        _util_Quantizer__Array = __prg.resolve_type(util, "Quantizer<core::Array>")?;
        _util_Histogram = __prg.resolve_type(util, "Histogram")?;
        _util_Queue = __prg.resolve_type(util, "Queue")?;
        _util_QuantizerSlotBound = __prg.resolve_type(util, "QuantizerSlotBound")?;
        _util_Quantizer = __prg.resolve_type(util, "Quantizer")?;
        _util_CustomQuantizer = __prg.resolve_type(util, "CustomQuantizer")?;
        _util_GaussianProfileSlot = __prg.resolve_type(util, "GaussianProfileSlot")?;
        _util_QuantizerSlotBound__Array = __prg.resolve_type(util, "QuantizerSlotBound<core::Array>")?;
        _util_Crypto = __prg.resolve_type(util, "Crypto")?;
        _util_HistogramBin = __prg.resolve_type(util, "HistogramBin")?;
        _util_Gaussian = __prg.resolve_type(util, "Gaussian")?;
        _util_GaussianProfile = __prg.resolve_type(util, "GaussianProfile")?;
        _util_Plot = __prg.resolve_type(util, "Plot")?;
        _util_LogQuantizer = __prg.resolve_type(util, "LogQuantizer")?;
        _util_TimeWindow = __prg.resolve_type(util, "TimeWindow")?;
        _util_MultiQuantizer = __prg.resolve_type(util, "MultiQuantizer")?;
        _util_Assert = __prg.resolve_type(util, "Assert")?;
        _util_HistogramStats = __prg.resolve_type(util, "HistogramStats")?;
        let project = __prg.resolve_module("project")?;
        _project_Record = __prg.resolve_type(project, "Record")?;
        _project_Root = __prg.resolve_type(project, "Root")?;
        let csv2 = __prg.resolve_module("csv2")?;
        _csv2_CsvReader__Record = __prg.resolve_type(csv2, "CsvReader<project::Record>")?;
        _csv2_CsvOptions = __prg.resolve_type(csv2, "CsvOptions")?;
        _csv2_CsvReader = __prg.resolve_type(csv2, "CsvReader")?;
        __prg.link_type_fn(_csv2_CsvReader, "can_read", csv2_CsvReader__can_read);
        __prg.link_type_fn(_csv2_CsvReader, "read", csv2_CsvReader__read);
    }
    use ::greycat::GcLibrary as _;
    crate::Library::init(__prg);
    Some(())
}

#[unsafe(no_mangle)]
unsafe extern "C" fn csv2_CsvReader__can_read(ctx: *mut ::greycat::sys::gc_machine_t) {
    let ctx = ::greycat::GcMachine(ctx);
    let this = unsafe { ctx.get_self_mut() };
    match crate::csv2::CsvReader::can_read(this, ctx) {
        Ok(value) => ctx.set_result(value),
        Err(err) => ctx.set_error(err),
    }
}

#[unsafe(no_mangle)]
unsafe extern "C" fn csv2_CsvReader__read(ctx: *mut ::greycat::sys::gc_machine_t) {
    let ctx = ::greycat::GcMachine(ctx);
    let this = unsafe { ctx.get_self_mut() };
    match crate::csv2::CsvReader::read(this, ctx) {
        Ok(value) => ctx.set_result(value),
        Err(err) => ctx.set_error(err),
    }
}
