[package]
name = "greycat-abi"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
greycat = { workspace = true }
greycat-gcb = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
ureq = "3.1.4"
