// AUTOMATICALLY GENERATED BY 'greycat codegen'
#![allow(non_snake_case)]

#[global_allocator]
static GLOBAL: ::greycat::GreyCatAlloc = ::greycat::GreyCatAlloc;

#[unsafe(no_mangle)]
pub unsafe extern "C" fn gc_lib_simple__link(
    prog: *mut ::greycat::sys::gc_program_t,
    lib: *mut ::greycat::sys::gc_program_library_t,
) -> bool {
    let __gc_prog = ::greycat::GcProgramMut(prog);
    unsafe {
        ::greycat::sys::gc_program_library__set_lib_hooks(
            lib,
            Some(simple_start),
            Some(simple_stop),
        );
    }

    let calc = __gc_prog.resolve_module("calc");
    let calc_DoubleInputCalc = __gc_prog.resolve_type(calc, "DoubleInputCalc");
    __gc_prog.configure_type(
        calc_DoubleInputCalc,
        ::std::mem::size_of::<crate::calc::DoubleInputCalc>(),
        crate::calc::_gc_DoubleInputCalc_finalize,
    );
    __gc_prog.link_type_fn(calc_DoubleInputCalc, "sum", crate::calc::_gc_DoubleInputCalc__sum);
    __gc_prog.link_type_fn(calc_DoubleInputCalc, "sub", crate::calc::_gc_DoubleInputCalc__sub);
    __gc_prog.link_mod_fn(calc, "sum", crate::calc::_gc_sum);
    __gc_prog.link_mod_fn(calc, "sub", crate::calc::_gc_sub);

    let io2 = __gc_prog.resolve_module("io2");
    __gc_prog.link_mod_fn(io2, "read_file", crate::io2::_gc_read_file);

    true
}

unsafe extern "C" fn simple_start(
    _lib: *mut ::greycat::sys::gc_program_library_t,
    prog: *mut ::greycat::sys::gc_program_t,
    userdata: *mut *mut ::core::ffi::c_void,
) -> bool {
    use ::greycat::GcLibrary as _;
    let prog = ::greycat::GcProgramMut(prog);
    match crate::LibState::start(prog) {
      Ok(Some(data)) => {
          let data = Box::new(data);
          unsafe { *userdata = Box::into_raw(data) as *mut _ };
          true
      }
      Ok(None) => true,
      Err(_) => false,
    }
}

unsafe extern "C" fn simple_stop(
    _lib: *mut ::greycat::sys::gc_program_library_t,
    prog: *mut ::greycat::sys::gc_program_t,
    userdata: *mut *mut ::core::ffi::c_void,
) -> bool {
    use ::greycat::GcLibrary as _;
    let prog = ::greycat::GcProgramMut(prog);
    let state = unsafe { crate::LibState::load(userdata) };
    crate::LibState::stop(prog, state).is_ok()
}

impl crate::calc::DoubleInputCalc {
    pub fn a(&self, ctx: ::greycat::GcMachine) -> i64 {
        use ::greycat::ObjectGetAt as _;
        unsafe { self.__header.get_at(0, ctx) }
    }
    pub fn b(&self, ctx: ::greycat::GcMachine) -> i64 {
        use ::greycat::ObjectGetAt as _;
        unsafe { self.__header.get_at(1, ctx) }
    }
}
